# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: halogen-hallucinations.github.io
title: HALoGEN
subTitle: Fantastic LLM Hallucinations and Where To Find Them
email: aravicha@cs.washington.edu
author: Abhilasha Ravichander
description: 'All materials for the paper "HALoGEN: Fantastic LLM Hallucinations and Where to Find Them".'
copyright: 'Copyright &copy; 2024 Abhilasha Ravichander. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Paper
    url: https://arxiv.org/abs/2102.08345
  - title: Bibtex
    url: ../bibtex
  - title: Dataset
    url: https://github.com/noiseQA/NoiseQA
  - title: Model Hallucinations
    url: https://github.com/noiseQA/noiseQA-gen
  - title: Video
    url: https://slideslive.com/38954510/noiseqa-challenge-set-evaluation-for-usercentric-question-answering
