# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: noiseqa.github.io
title: NoiseQA
subTitle: Challenge Set Evaluation for User-Centric Question Answering
email: aravicha@cs.cmu.edu
author: Abhilasha Ravichander
description: 'All materials for the paper "NoiseQA: Challenge Set Evaluation for User-Centric Question Answering", published at EACL 2021.'
copyright: 'Copyright &copy; 2020 Abhilasha Ravichander. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Paper
    url: https://arxiv.org/abs/2102.08345
  - title: Bibtex
    url: ../bibtex
  - title: Dataset
    url: https://github.com/noiseQA/NoiseQA
  - title: Noise Generators
    url: https://github.com/noiseQA/noiseQA-gen
  - title: Video
    url: https://slideslive.com/38954510/noiseqa-challenge-set-evaluation-for-usercentric-question-answering
